# Generated by Django 3.1.7 on 2021-04-29 06:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_internshipapplieddb_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipapplieddb',
            name='internship_id',
        ),
        migrations.AddField(
            model_name='internshipapplieddb',
            name='applied_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipapplieddb',
            name='internship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appliedInternship', to='company.internship'),
        ),
        migrations.AddField(
            model_name='internshipapplieddb',
            name='internshipkey',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='internshipapplieddb',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
