# Generated by Django 3.1.7 on 2021-04-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20210429_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplieddb',
            name='applied_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
