# Generated by Django 3.1.7 on 2021-04-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20210429_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='no_of_applicants',
            field=models.IntegerField(default=0),
        ),
    ]
