# Generated by Django 3.1.7 on 2021-04-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_resume_resume_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('std_id', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('company_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('complition_year', models.IntegerField()),
                ('resume_file', models.ImageField(blank=True, null=True, upload_to='student/certificate/')),
            ],
        ),
    ]
