# Generated by Django 3.1.7 on 2021-04-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='credential',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
